#
# Hardware settings for ASUSTeK COMPUTER INC. ZenBook Pro Duo UX582ZM_UX582ZM
# Dual boot active. Windows @ /dev/nvme0n1p3 (label OS) / NixOS @ /dev/nvme0n1p9 (label nixos)
#
# flake.nix
#  └─ ./hosts
#      └─ ./laptop
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C6B3-561C";
      fsType = "vfat";
    };

  # swapDevices = [ ];
  swapDevices =
    [
    ];

  networking.useDHCP = lib.mkDefault true;
  # networking = {
  #   useDHCP = false;                        # Deprecated
  #   hostName = "z2";
  #   networkmanager.enable = true;
  #   interfaces = {
  #     enp0s25 = {
  #       useDHCP = true;                     # For versatility sake, manually edit IP on nm-applet.
  #       #ipv4.addresses = [ {
  #       #    address = "192.168.0.51";
  #       #    prefixLength = 24;
  #       #} ];
  #     };
  #     wlo1 = {
  #       useDHCP = true;
  #       #ipv4.addresses = [ {
  #       #  address = "192.168.0.51";
  #       #  prefixLength = 24;
  #       #} ];  
  #     };
  #   };
  #   defaultGateway = "192.168.0.1";
  #   nameservers = [ "192.168.0.1" "1.1.1.1"];
  #   firewall = {
  #     enable = false;
  #     #allowedUDPPorts = [ 53 67 ];
  #     #allowedTCPPorts = [ 53 80 443 9443 ];
  #   };
  # };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
